### ISSUE TITLE
[Crash] [CalendarDialog] Can navigate to disabled months after going back and forth, leading to a crash

### ISSUE THREAD

**Issue by Nek-12** [maxkeppeler/sheets-compose-dialogs#19]
To reproduce:

1. Open a Calendar Dialog, setting CalendarTimeline to PAST
2. Navigate to the month that's after the current one
3. Quickly return back while the button is animating away
4. Go back several months. You are now able to navigate between disabled months
5. Go back to the year that's disabled. For example, go from Jan 2023 to Dec 2022
6. Tap on the year selection (2022 text)
7. Year selection opens but current year is not shown
8. Tap anywhere
9. App crashes with the following stacktrace

```
Fatal Exception: java.lang.IllegalArgumentException: Index should be non-negative (-1)
       at androidx.compose.foundation.lazy.LazyListScrollPosition.update-AhXoVpI(LazyListScrollPosition.kt:101)
       at androidx.compose.foundation.lazy.LazyListState.l(LazyListState.kt:2)
       at androidx.compose.foundation.lazy.LazyListState$scrollToItem$2.invokeSuspend(LazyListState.kt:244)
       at androidx.compose.foundation.lazy.LazyListState$scrollToItem$2.invoke(LazyListState.kt:12)
       at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invokeSuspend(ScrollableState.kt:178)
       at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1.invoke(ScrollableState.kt:12)
       at androidx.compose.foundation.MutatorMutex$mutateWith$2.invokeSuspend(MutatorMutex.kt:160)
       at androidx.compose.foundation.MutatorMutex$mutateWith$2.invoke(MutatorMutex.kt:12)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(UndispatchedKt.java:89)
       at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScopeKt.java:264)
       at androidx.compose.foundation.MutatorMutex.mutateWith(MutatorMutex.kt:153)
       at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invokeSuspend(ScrollableState.kt:175)
       at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2.invoke(ScrollableState.kt:12)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(UndispatchedKt.java:89)
       at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScopeKt.java:264)
       at androidx.compose.foundation.gestures.DefaultScrollableState.scroll(ScrollableState.kt:174)
       at androidx.compose.foundation.lazy.LazyListState.scroll(LazyListState.kt:268)
       at androidx.compose.foundation.gestures.ScrollableState.scroll$default(ScrollableState.java:53)
       at androidx.compose.foundation.lazy.LazyListState.scrollToItem(LazyListState.kt:243)
       at androidx.compose.foundation.lazy.LazyListState.scrollToItem$default(LazyListState.java:238)
       at com.maxkeppeler.sheets.calendar.CalendarViewKt$CalendarView$1.invokeSuspend(CalendarView.kt:72)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:2)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7913)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

**Comment by Nek-12** [comment]
This is unfortunately already on prod for us 😬

**Comment by maxkeppeler** [comment]
I'm just fixing the origin of the exception. The buttons shouldn't allow redirecting any clicks when animating them away. I wouldn't worry, as it's not exactly easy to trigger that button quick enough. Nice catch!
