### ISSUE TITLE
Crash: No static method TextButton

### ISSUE THREAD

**Issue by Nek-12** [maxkeppeler/sheets-compose-dialogs#4]
Crash on entering composition with ClockComponent

```
compose-material3 = "1.1.0-alpha01"
compose = "1.4.0-alpha01"
compose-activity = "1.7.0-alpha02"
compose-compiler = "1.3.2"
```

```
java.lang.NoSuchMethodError: No static method TextButton(Lkotlin/jvm/functions/Function0;Landroidx/compose/ui/Modifier;ZLandroidx/compose/foundation/interaction/MutableInteractionSource;Landroidx/compose/material3/ButtonElevation;Landroidx/compose/ui/graphics/Shape;Landroidx/compose/foundation/BorderStroke;Landroidx/compose/material3/ButtonColors;Landroidx/compose/foundation/layout/PaddingValues;Lkotlin/jvm/functions/Function3;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/material3/ButtonKt; or its super classes (declaration of 'androidx.compose.material3.ButtonKt' appears in /data/app/~~Hfpewa0d1yNCgujP5fX8aQ==/com.example.package-7oldB481MCd-Oz-IEPAD-A==/base.apk)
                            	at com.maxkeppeker.sheets.core.views.ButtonsComponentKt.SelectionButtonComponent(ButtonsComponent.kt:125)
                            	at com.maxkeppeker.sheets.core.views.ButtonsComponentKt.ButtonsComponent(ButtonsComponent.kt:70)
                            	at com.maxkeppeler.sheets.clock.ClockViewKt$ClockView$2.invoke(ClockView.kt:73)
                            	at com.maxkeppeler.sheets.clock.ClockViewKt$ClockView$2.invoke(ClockView.kt:72)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at com.maxkeppeker.sheets.core.views.base.FrameBaseKt.FrameBase(FrameBase.kt:98)
                            	at com.maxkeppeler.sheets.clock.ClockViewKt.ClockView(ClockView.kt:52)
                            	at com.maxkeppeler.sheets.clock.ClockDialogKt$ClockDialog$1.invoke(ClockDialog.kt:51)
                            	at com.maxkeppeler.sheets.clock.ClockDialogKt$ClockDialog$1.invoke(ClockDialog.kt:50)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:129)
                            	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:113)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                            	at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:110)
                            	at com.maxkeppeker.sheets.core.views.base.DialogBaseKt$DialogBase$4.invoke(DialogBase.kt:80)
                            	at com.maxkeppeker.sheets.core.views.base.DialogBaseKt$DialogBase$4.invoke(DialogBase.kt:64)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1$2.invoke(AndroidDialog.android.kt:181)
                            	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1$2.invoke(AndroidDialog.android.kt:180)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.ui.window.AndroidDialog_androidKt.DialogLayout(AndroidDialog.android.kt:496)
                            	at androidx.compose.ui.window.AndroidDialog_androidKt.access$DialogLayout(AndroidDialog.android.kt:1)
                            	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1.invoke(AndroidDialog.android.kt:178)
                            	at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1.invoke(AndroidDialog.android.kt:175)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.ui.window.DialogLayout.Content(AndroidDialog.android.kt:272)
                            	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:250)
                         E  	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:249)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                            	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:177)
                            	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
                            	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                            	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:156)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
                            	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3274)
                            	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3264)
                            	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                            	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                            	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3264)
                            	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3199)
                            	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
                            	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:950)
                            	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3874)
                            	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3874)
                            	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                            	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1063)
                            	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
                            	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
                            	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
                            	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:203)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
                         E  	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                            	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1150)
                            	at android.view.View.dispatchAttachedToWindow(View.java:21291)
                            	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
                            	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                            	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                            	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                            	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
                            	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2771)
                            	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
                            	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
                            	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
                            	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                            	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                            	at android.view.Choreographer.doFrame(Choreographer.java:832)
                            	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                            	at android.os.Handler.handleCallback(Handler.java:942)
                            	at android.os.Handler.dispatchMessage(Handler.java:99)
                            	at android.os.Looper.loopOnce(Looper.java:201)
                            	at android.os.Looper.loop(Looper.java:288)
                            	at android.app.ActivityThread.main(ActivityThread.java:7898)
                            	at java.lang.reflect.Method.invoke(Native Method)
                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by maxkeppeler** [comment]
I guess that's because you are using the alpha release of Compose Material Design 3. I will bump the dependencies to the latest stable release versions, but avoid the latest alpha releases. Which makes sense for a library, IMO. Can u downgrade the MD3 dependency and check if it works then?

**Comment by Nek-12** [comment]
It's certainly not the alpha release at fault.
Alpha01 has no api changes and no functions were removed.
But I think it's because your project uses pretty outdated compose and material3 versions overall. Updating to latest stables should fix the issue

**Comment by maxkeppeler** [comment]
I did not mean that the alpha release is at fault, but indeed the diff between your versions and the versions of the lib. I agree and will update the dependencies soon.

**Comment by Nek-12** [comment]
Thank you for being so responsive

**Comment by Nek-12** [comment]
Should I open a PR with updates to the dependencies?

**Comment by maxkeppeler** [comment]
I can only work on it on the weekends. I think a PR isn't necessary as I've already changed it and will commit it and anyway have to publish a new version, so no need! Definitely this evening or on Sunday!

**Comment by maxkeppeler** [comment]
1.0.1 has updated the dependencies to the latest stable version.
